name: 'Install Dependencies'

inputs:
  requirements: # This input is optional.
    description: 'Path to the requirements file'
    required: false
  install: # This input is optional.
    description: 'List of packages to install'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      env:
        PYTHON_VERSION: 3.9
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r src/requirements.txt
          pip install pyinstaller
          pip install Pillow
