name: Build workflow

on:
  push:
    tags:
      - v[0-9]+.* # this regular expression matches tags like v1.0.0, v2.3.4, etc.
    branches:
      - main
  workflow_call:
    inputs:
      tag_name:
        type: string
      draft:
        type: string
      prerelease:
        type: string
      generate_release_notes:
        type: string

# write permission is needed for github release job.
permissions:
  contents: write

# The workflow consists of three jobs: lint, tests, and build.

jobs:

  tests:
    uses: ./.github/workflows/unit-tests.yml

  build:
    name: build and upload artifacts
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            target: windows
          - os: ubuntu-latest
            arch: amd64
            target: linux
          - os: macos-latest
            arch: amd64
            target: darwin
          - os: macos-latest
            arch: arm64
            target: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install python dependencies
        uses: ./.github/actions/install
      - name: Install linux dependencies
        if: ${{ matrix.target == 'linux'}}
        run: sudo apt install qt6-base-dev
      - name: Build ThyraApp application
        run: pyinstaller src/ThyraApp.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ThyraApp_${{ matrix.target }}-${{ matrix.arch }}
          path: dist
      - name: Rename binary
        if: ${{ matrix.target != 'windows'}}
        run: mv dist/ThyraApp ThyraApp_${{ matrix.target }}-${{ matrix.arch }}
      - name: Rename binary windows
        if: ${{ matrix.target == 'windows'}}
        run: mv dist/ThyraApp.exe ThyraApp_${{ matrix.target }}-${{ matrix.arch }}.exe
      - name: Create release and upload binaries
        if: ${{ inputs.tag_name != ''}}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: ${{ inputs.generate_release_notes }}
          files: ThyraApp_*
