# This is a configuration file for a GitHub Actions workflow.
# The workflow is triggered when a versioned tag is pushed to the main branch,
# or when a pull request is opened or when the workflow is manually called.
on:
  push:
    tags:
      - v[0-9]+.* # this regular expression matches tags like v1.0.0, v2.3.4, etc.
    branches:
      - main
  pull_request:
  workflow_call:

# The contents of the repository should be readable by the workflow.
permissions:
  contents: read

# The workflow consists of three jobs: lint, tests, and build.

jobs:

  tests:
    uses: ./.github/workflows/tests.yml

  build:
    name: build and upload artifacts
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            target: windows
          - os: ubuntu-latest
            arch: amd64
            target: linux
          - os: macos-latest
            arch: amd64
            target: darwin
          - os: macos-latest
            arch: arm64
            target: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: ./.github/actions/install
      - name: Build ThyraApp application
        run: pyinstaller src/ThyraApp.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ThyraApp_${{ matrix.target }}_${{ matrix.arch }}
          path: dist